language: powershell
os: windows
script: pwsh -f hello.psl

#deploy:
#  provider: releases
#  api_key:
#    secure: bJ+jjOsLtRl/cEvptYrYX7EQoF6zSCtmWyGzLehiK9LCLq8h9qnFceUdIQI7BJEUM/ToeEeKm+aUltK011jTbELTpB82kI88XCpQLfAL4xATmtpSnl0vs8FwVl5dL9grukSc+f7vEShPEYMfzQYTMxu9LEO1+1h5p0rqdqafs/3lRJNZU55sLcf7b0INfNfPP3yiwQvVfE0H06hwaEuW10xP/nb+r3lQS2VmDWVWuFLTKxm1FWoG+TMpFKC6e8yjRvgl74E+JKJRL2JXEYtDuvHl2Y7/QogFcC99Af4FB8RkCSZk4Y/gcwfPM/4zN38YbL0qOz0S32mEnExfjNTlH39NnI4NW9X7vZNlQWgJTqMQLqG3qpwO1PCrTWcYPvqxL21BSThi0DcfF9icThD8GQhXKDBqIo8EeWEFfjxIYoSHirCB9PoTe0qsocq3xZSw/6Vsze0KoOgzWjiWLlanov+dSGV1V7/WT+32s1AmT4aDUbzMJuhjj/y6rID7XzPWaDNaMRkZIbLGhHI9tD0rjLe1UyY6pgT4tRhIdL6EoqyMDOKqNgqUvxeN8j7TCEQ9GQQrgOpRR7vRAUeecs2jnQ0O216bWumRl3qn+rpJbZ/ExrIZkaMO0edS9KEftI1LhCJBAgArR3N/yGYgCLOHGnPWq5naj6ge+5xvis5cd+w=
#  on:
#    repo: anthshor/powershell-hello
